In [32]:
import pandas as pd

In [33]:
machine_learning_df = pd.read_csv('Data/machine_learning_df.csv')

In [34]:
reddit_buzzwords_df = pd.read_csv('reddit_buzzwords.csv')

In [35]:
google_buzzwords_df = pd.read_csv('google_buzzwords.csv')

In [36]:
combined_df = pd.concat([machine_learning_df, reddit_buzzwords_df, google_buzzwords_df], axis=1)

In [37]:
combined_df.head()

,Unnamed: 0,date,open,high,low,close,volume,returns,class,google trend,...,Reddit negative,Google compound,Google positive,Google negative,Unnamed: 0,index,reddit buzzword score,Unnamed: 0,index,google buzzword score
0,0,2017-08-18,4285.08,4371.52,3938.77,4108.37,1199.888264,-0.041238,0,1967,...,0.082,0.9848,0.150,0.000,0,0,146.333495,0,0,9.736044
1,1,2017-08-19,4108.37,4184.69,3850.00,4139.98,381.309763,0.007694,0,1844,...,0.090,0.7096,0.059,0.027,1,1,187.989746,1,1,6.715108
2,2,2017-08-20,4120.98,4211.08,4032.62,4086.29,467.083022,-0.012969,0,1704,...,0.109,0.8910,0.076,0.017,2,2,200.210838,2,2,7.921181
3,3,2017-08-21,4069.13,4119.62,3911.79,4016.00,691.743060,-0.017201,0,1702,...,0.104,0.6359,0.111,0.076,3,3,162.376347,3,3,7.465451
4,4,2017-08-22,4016.00,4104.82,3400.00,4040.00,966.684858,0.005976,0,1893,...,0.108,0.6808,0.065,0.036,4,4,164.760500,4,4,8.167459

In [38]:
combined_df.columns

Index(['Unnamed: 0', 'date', 'open', 'high', 'low', 'close', 'volume',
       'returns', 'class', 'google trend', 'Reddit compound',
       'Reddit positive', 'Reddit negative', 'Google compound',
       'Google positive', 'Google negative', 'Unnamed: 0', 'index',
       'reddit buzzword score', 'Unnamed: 0', 'index',
       'google buzzword score'],
      dtype='object')

In [39]:
combined_df = combined_df[['date', 'class', 'volume', 'google trend','Reddit positive', 'Reddit negative','Google positive', 'Google negative','reddit buzzword score','google buzzword score']]

In [40]:
combined_df.set_index('date', inplace=True)

In [41]:
combined_df.head()

,class,volume,google trend,Reddit positive,Reddit negative,Google positive,Google negative,reddit buzzword score,google buzzword score
date,,,,,,,,,
2017-08-18,0,1199.888264,1967,0.132,0.082,0.150,0.000,146.333495,9.736044
2017-08-19,0,381.309763,1844,0.122,0.090,0.059,0.027,187.989746,6.715108
2017-08-20,0,467.083022,1704,0.128,0.109,0.076,0.017,200.210838,7.921181
2017-08-21,0,691.743060,1702,0.129,0.104,0.111,0.076,162.376347,7.465451
2017-08-22,0,966.684858,1893,0.131,0.108,0.065,0.036,164.760500,8.167459

In [42]:
combined_df.to_csv('combined_df.csv')

In [43]:
combined_df['class'].value_counts()

 0    1391
 1      36
-1      23
Name: class, dtype: int64